apiVersion: apps/v1
kind: Deployment
metadata:
  name:  flask-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name:  flask
        image:  pvctest:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  5000
        volumeMounts:
        - name: flask-storage
          mountPath: /data
      volumes:
        - name: flask-storage
          persistentVolumeClaim:
            claimName: flask-pvc