apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: default
spec:
  selector:
    app: flask
  type: NodePort
  ports:
  - name: flask
    protocol: TCP
    port: 80
    targetPort: 5000