apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
  namespace: test-ns
spec:
  selector:
    app: flask-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080