apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  namespace: env-vars
  labels:
    purpose: demo-envars
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: DEMO_GREETING
      value: "hELLO FROM THE ENVIRONMENT"
    - name: DEMO_FAREWELL
      value: "Such sweet sorrow"