apiVersion: v1
kind: Pod
metadata:
  name: print-greeting
  namespace: env-vars
spec:
  containers:
  - name: env-print-demo
    image: bash
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: GREETING
      value: "Warm greetings to"
    - name: HONORIFIC
      value: "The Most HOnorable"
    - name: NAME
      value: "Kuberentes"
    - name: MESSAGE
      value: "$(GREETING) $(HONORIFIC) $(NAME)"
    command: ["echo"]
    args: ["$(MESSAGE)"]
